#!/bin/sh

cd /data/repo/
echo Mirroring SL7x...
rsync -avkSH --delete --delete-after --exclude=archive/debuginfo --exclude=archive/obsolete --exclude=SRPMS rsync://rsync.scientificlinux.org/scientific/7x/x86_64/os /data/repo/sl7x/
echo Mirroring SL7x updates...
rsync -avkSH --delete --delete-after --exclude=archive/debuginfo --exclude=archive/obsolete --exclude=SRPMS rsync://rsync.scientificlinux.org/scientific/7x/x86_64/updates /data/repo/sl7x/
echo Mirroring SL7x extras
rsync -avkSH --delete --delete-after --exclude=archive/debuginfo --exclude=archive/obsolete --exclude=SRPMS rsync://rsync.scientificlinux.org/scientific/7x/external_products /data/repo/sl7x/
echo Mirroring RDO...
wget -c -m -np http://mirror.centos.org/centos/7/cloud/x86_64/openstack-liberty/
echo Mirroring EPEL...
wget -c -m -np http://mirror.speedpartner.de/epel/7/
echo Mirroring SL7x SRPMS...
rsync -avkSH --delete --delete-after --exclude=archive/debuginfo --exclude=archive/obsolete --exclude=SRPMS rsync://rsync.scientificlinux.org/scientific/7x/SRPMS /data/repo/sl7x/
